[package]
name = "repsheet_etl"
version = "0.0.4"
authors = ["Aaron Bedra <aaron@aaronbedra.com>"]
license = "Apache-2.0"
repository = "https://github.com/abedra/repsheet_etl"
description = "ETL tools for repsheet"

[dependencies]
itertools = "0.9.0"
glob = "0.3.0"
either = "1.6.1"